### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)
matrix = np.array([[11,14,17],
                  [20,23,26],
                  [29,32,35]])
print('Вектор: ', vector)
print('Розмір вектору: ', vector.shape)
print('Матриця:', matrix)
print('Розмір матриці: ', matrix.shape)

Вектор:  [0.76381313 0.76558886 0.34130949 0.41197838 0.28032375 0.96086251
 0.70265168 0.88267478 0.10038133 0.24587118]
Розмір вектору:  (10,)
Матриця: [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці:  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [3]:
np.round((vector+10),2)

array([10.76, 10.77, 10.34, 10.41, 10.28, 10.96, 10.7 , 10.88, 10.1 ,
       10.25])

In [4]:
np.dot(matrix,2)

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [5]:
sq_vector = np.square(vector)
sq_vector

array([0.5834105 , 0.5861263 , 0.11649217, 0.16972619, 0.07858141,
       0.92325676, 0.49371938, 0.77911476, 0.01007641, 0.06045264])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [7]:
result_matrix = np.dot(B,A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [8]:
np.dot(result_matrix,C)

array([[0.5202],
       [0.2846]])

In [9]:
np.dot(result_matrix,D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [10]:
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [11]:
vector_T = vector.T
print(vector_T, vector_T.shape)

[0.76381313 0.76558886 0.34130949 0.41197838 0.28032375 0.96086251
 0.70265168 0.88267478 0.10038133 0.24587118] (10,)


In [12]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector, column_vector.shape)

[[0.76381313]
 [0.76558886]
 [0.34130949]
 [0.41197838]
 [0.28032375]
 [0.96086251]
 [0.70265168]
 [0.88267478]
 [0.10038133]
 [0.24587118]] (10, 1)


In [13]:
column_vector_T = column_vector.T
print(column_vector_T, column_vector_T.shape)

[[0.76381313 0.76558886 0.34130949 0.41197838 0.28032375 0.96086251
  0.70265168 0.88267478 0.10038133 0.24587118]] (1, 10)
